services:
  coffee4u:
    image: mysql
    container_name: coffee4u
    restart: always
    ports:
      - 3303:3306
    environment:
      MYSQL_DATABASE: "coffee4u"
      MYSQL_USER: "coffee4u"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    expose:
      - 3303
    volumes:
      - ./coffee4u:/var/lib/mysql

volumes:
  coffee4u: